### PR TITLE
Fix issue #1039 and #1046

### LINKED ISSUE #1039: KCM (deployment controller) on TP cluster failed to sync up deployment with its token
**What happened**:

KCM (deployment controller) on TP cluster failed to sync up deployment with its token.

```
I0321 00:18:52.347999       1 deployment_controller.go:563] Started syncing deployment "arktos/v8uy5l-testns/saturation-deployment-0" (2021-03-21 00:18:52.347985815 +0000 UTC m=+665.382452865)
I0321 00:18:52.348391       1 deployment_util.go:260] Updating replica set "saturation-deployment-0-c47675f5" revision to 1
I0321 00:18:52.352163       1 deployment_controller.go:565] Finished syncing deployment "arktos/v8uy5l-testns/saturation-deployment-0" (4.172689ms)
I0321 00:18:52.352185       1 deployment_controller.go:485] Error syncing deployment arktos/v8uy5l-testns/saturation-deployment-0: replicasets.apps is forbidden: User "system:kube-controller-manager" cannot create resource "replicasets" in API group "apps" in the 
namespace "v8uy5l-testns"
```

append_or_replace_prefixed_line "${known_tokens_csv}" "${KUBE_CONTROLLER_MANAGER_TOKEN}," "system:kube-controller-manager,uid:system:kube-controller-manager"

**What you expected to happen**:
the controller should be permitted to perform the replication sets and create pods on the deployment

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sonyafenge**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:
Fix issue #1039 and #1046
**Which issue(s) this PR fixes**:

Fixes #1039 #1046 

**Special notes for your reviewer**:
500 nodes run for 1tp*1rp passed for both load and density using this build: https://github.com/futurewei-cloud/arktos-perftest/commits/perf-20210326. 
Logs can be found under GCP project: workload-controller-manager on sonyadev4: /home/sonyali/logs/perf-test/gce-500/arktos/fix1038-032621-1x1x500

500 nodes run for 2tp*1rp passed for both load and density using this build: https://github.com/futurewei-cloud/arktos-perftest/commits/perf-20210330. 
Logs can be found under GCP project: workload-controller-manager on sonya-uswest2: /home/sonyali/logs/perf-test/gce-500/arktos/perf033021-2x1x500
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: cluster/gce/gci/configure-helper-common.sh [hunk 1]
```diff
@@ -2328,9 +2328,9 @@ function start-kube-controller-manager {
   prepare-log-file /var/log/kube-controller-manager.log
   # Calculate variables and assemble the command line.
   local params="${CONTROLLER_MANAGER_TEST_LOG_LEVEL:-"--v=4"} ${CONTROLLER_MANAGER_TEST_ARGS:-} ${CLOUD_CONFIG_OPT}"
-  if [[ "${KUBERNETES_RESOURCE_PARTITION:-false}" == "false" ]] && [[ "${KUBERNETES_TENANT_PARTITION:-false}" == "false" ]]; then
+  #if [[ "${KUBERNETES_RESOURCE_PARTITION:-false}" == "false" ]] && [[ "${KUBERNETES_TENANT_PARTITION:-false}" == "false" ]]; then
```
Comment (yb01) [inline cluster/gce/gci/configure-helper-common.sh:2331]: I think we can go ahead remove this commented lines.

**Review by yb01 — APPROVED** [review]
/lgtm

**Review by chenqianfzh — APPROVED** [review]

**Review by XiaoningDing — APPROVED** [review]
