### PR TITLE
kube-up.sh support Daemonset for scale-out

### LINKED ISSUE #1270: [kube-up] [scale-out] RP master node should be able to have pods scheduled on
**What happened**:
in kube-up 1x1 scale-out env, RP master is unable to have pod scheduled on, as illustrated as below
```
# kubectl get node
NAME                          STATUS                     ROLES    AGE     VERSION
hwc-kubeup-test-rp-1-master   Ready,SchedulingDisabled   <none>   8m29s   v0.9.0
```

**What you expected to happen**:
in scale-out arch, RP master is be default able to have pods scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
run kube-up script (of poc-2022-01-30) to start 1x1 scale-out cluster (besides the regular env vars for successful kube-up run)
```
export SCALEOUT_CLUSTER=true SCALEOUT_TP_COUNT=1 SCALEOUT_RP_COUNT=1
./cluster/kube-up.sh
```

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration: GCP + kube-up
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.3 LTS (RP master)
- Kernel (e.g. `uname -a`): 5.11.0-1023-gcp (RP master)
- Install tools: kube-up, scale-out, ubuntu-focal image
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sonyafenge**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:
1. scale-out TP server enable Daemonset controller
2. add tenant-server-kubeconfig for rp kubelet

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by h-w-chen — APPROVED** [review]
lgtm

File: cluster/gce/gci/configure-helper.sh [hunk 1]
```diff
@@ -143,7 +143,9 @@ function main() {
     start-lb-controller
     update-legacy-addon-node-labels &
     apply-encryption-config &
-    start-cluster-networking   ####start cluster networking if not using default kubenet
+    if [[ "${ARKTOS_SCALEOUT_SERVER_TYPE:-}" != "rp" ]]; then
```
Comment (yb01) [inline cluster/gce/gci/configure-helper.sh:146]: it would be clearer to use ARKTOS_SCALEOUT_SERVER_TYPE in desiredTypes, to start the container network explicitly on the needed servers, currently the ARKTOS_SCALEOUT_SERVER_TYPE can be node, tp, rp, proxy and this might be expand as well. this way,  some unwanted calls can be avoided here.

File: cluster/gce/gci/configure-helper-common.sh [hunk 2]
```diff
@@ -2347,7 +2347,7 @@ function start-kube-controller-manager {
     RUN_CONTROLLERS="serviceaccount,serviceaccount-token,nodelifecycle,ttl,daemonset,csrsigning,csrapproving,csrcleaner"
   fi
   if [[ "${ARKTOS_SCALEOUT_SERVER_TYPE:-}" == "tp" ]]; then
-    RUN_CONTROLLERS="*,-nodeipam,-nodelifecycle,-mizar-controllers,-network,-ttl,-daemonset"
+    RUN_CONTROLLERS="*,-nodeipam,-nodelifecycle,-mizar-controllers,-network,-ttl"
```
Comment (yb01) [inline cluster/gce/gci/configure-helper-common.sh:2350]: please remove the daemonset controller from the RP as well with this change to make it complete.

**Review by yb01 — APPROVED** [review]
/lgtm. you might want to get this to master as well since DS code change has been merged to there to support DS from TP instead of RP.

File: cluster/gce/gci/configure-helper-common.sh (hunk 2 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper-common.sh:2350]: Do you mean we don't need Daemonset for RP? we need double check this. For now, local environments has both enabled Daemonset.

Comment (Sindica) [reply cluster/gce/gci/configure-helper-common.sh:2350]: In theory, Daemonset controller should not be running in RP. I will take it off and test in local env.

Comment (Sindica) [reply cluster/gce/gci/configure-helper-common.sh:2350]: I have tested in local dev env, daemonset controller can be disabled for RP.

File: cluster/gce/gci/configure-helper-common.sh [hunk 3]
```diff
@@ -2347,7 +2347,7 @@ function start-kube-controller-manager {
     RUN_CONTROLLERS="serviceaccount,serviceaccount-token,nodelifecycle,ttl,daemonset,csrsigning,csrapproving,csrcleaner"
```
Comment (Sindica) [inline cluster/gce/gci/configure-helper-common.sh:2347]: Please remove daemonset controller from rp.

File: cluster/gce/gci/configure-helper-common.sh (hunk 2 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper-common.sh:2350]: removed

File: cluster/gce/gci/configure-helper.sh (hunk 1 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper.sh]: updated in new commit

File: cluster/gce/gci/configure-helper-common.sh (hunk 3 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper-common.sh]: removed
