### PR TITLE
kube-up.sh not use  DISABLE_ADMISSION_PLUGINS env var

### LINKED ISSUE #1326: [kube-up][scale-out] TP master server is not up when DISABLE_ADMISSION_PLUGINS is not empty
**What happened**:
During starting procedure, the following error comes out.
```
DBG: MASTER_EXTRA_METADATA : 
ERROR: (gcloud.compute.instances.create) Unable to read file [/tmp/tmp.2v0tQQ1O62/network.tmpl]: [Errno 2] No such file or directory: '/tmp/tmp.2v0tQQ1O62/network.tmpl'
Failed to create master instance due to non-retryable error
```
**What you expected to happen**:
TP master server should be up when DISABLE_NETWORK_SERVICE_SUPPORT=true

**How to reproduce it (as minimally and precisely as possible)**:

./cluster/kube-up.sh

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: 1 x 1 kube-up
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by h-w-chen**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
this PR removes uses of DISABLE_ADMISSION_PLUGINS from kube-up script.

**Which issue(s) this PR fixes**:

Fixes #1326

**Special notes for your reviewer**:
this PR was extracted from PR #1327, so as to make the code focused.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cluster/gce/config-test.sh [hunk 1]
```diff
@@ -486,6 +482,9 @@ if [[ -z "${KUBE_ADMISSION_CONTROL:-}" ]]; then
     FEATURE_GATES="${FEATURE_GATES},InPlacePodVerticalScaling=true"
     ADMISSION_CONTROL="${ADMISSION_CONTROL},PodResourceAllocation"
   fi
+  if [[ -n ${DISABLE_NETWORK_SERVICE_SUPPORT:-} ]]; then # when network service is enabled
```
Comment (h-w-chen) [inline cluster/gce/config-test.sh:485]: should be -z

**Review by sonyafenge — APPROVED** [review]
/LGTM
