### PR TITLE
register network crd only for kube-up, not for kubemark

### LINKED ISSUE #1280: [kubemark][scale-out] kubemark.sh aborts with cluster/kubeconfig.tp-1 error
**What happened**:
kubemark.sh aborted with file not found error (e.g. cluster/kubeconfig.tp-1)

**What you expected to happen**:
kubemark should be able to run w/o error

**How to reproduce it (as minimally and precisely as possible)**:
run perf test by kube-up + kubemark (scale-out)

**Anything else we need to know?**:
it is regression introduced by #1278. 
The problematic code piece is in function kube-up
```
for num in $(seq ${SCALEOUT_TP_COUNT:-1}); do
        "${KUBE_ROOT}/cluster/kubectl.sh" --kubeconfig="cluster/kubeconfig.tp-${num}" apply -f "${KUBE_ROOT}/pkg/controller/artifacts/crd-network.yaml"
done
```
The code is called by both kube-up.sh and start-kubemark.sh.  When called by kubeamrk.sh, the cluster/kubeconfig.tp-${num} files are not right.

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: kubemark (scale-out)
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by h-w-chen**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR only registers network CRD at all TPs in kube-up scale-out, not in kubemark scale-out.

There was a regression introduced by #1278, which registers network CRD during scale-out start up process. For perf test, start-kubemark will hit the code and could not find the kubeconfig files named for kube-up scale-out TPs. The fix is NOT to register this CRD for kubemark, as kubemark does not really need such for testing.

**Which issue(s) this PR fixes**:

Fixes #1280

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -2684,10 +2684,12 @@ function kube-up() {
       done
       restart_tp_scheduler_and_controller
 
-      echo "DBG: defining CRD networks.arktos.futurewei.com at all TPs"
-      for num in $(seq ${SCALEOUT_TP_COUNT:-1}); do
-        "${KUBE_ROOT}/cluster/kubectl.sh" --kubeconfig="cluster/kubeconfig.tp-${num}" apply -f "${KUBE_ROOT}/pkg/controller/artifacts/crd-network.yaml"
-      done
+      if [[ "${PROVISION_MODE:-}" == "kube-up" ]]; then
```
Comment (sonyafenge) [inline cluster/gce/util.sh:2687]: suggest to use this exiting var:  if [[ "${KUBEMARK_PREFIX:-}" == "" ]]; then

we have this set when kubemark:
KUBEMARK_PREFIX="${KUBEMARK_PREFIX:-.kubemark}"

Comment (h-w-chen) [reply cluster/gce/util.sh:2687]: good hint. will take its advantage.

**Review by sonyafenge — APPROVED** [review]
/LGTM
