### PR TITLE
Start arktos-network-controller for kube-up

### LINKED ISSUE #1297: Start  arktos-network-controller for kube-up
**What happened**:
arktos-up already support arktos-network-controller, but kube-up still doesn't support. this should be fixed.
**What you expected to happen**:
kube-up support arktos-network-controller and default start it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/CentaurusInfra/arktos/pull/1190
https://github.com/CentaurusInfra/arktos/pull/1198
https://github.com/CentaurusInfra/arktos/pull/1199

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sonyafenge**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:
add arktos-network-controller start for kube-up

**Which issue(s) this PR fixes**:

Fixes #1297 

**Special notes for your reviewer**:
arktos-network-controller fully function need fix Issue #1279

metrics-server, kubernetes-dashboard, heapster pods failed with error:
```
failed to get DNS IP address: network system/default not found"
```

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: build/debian-hyperkube-base/Dockerfile [hunk 1]
```diff
@@ -27,6 +27,7 @@ RUN ln -s /hyperkube /apiserver \
  && ln -s /hyperkube /usr/local/bin/kube-apiserver \
  && ln -s /hyperkube /usr/local/bin/kube-controller-manager \
  && ln -s /hyperkube /usr/local/bin/workload-controller-manager \
+ && ln -s /hyperkube /usr/local/bin/arktos-network-controller \
```
Comment (h-w-chen) [inline build/debian-hyperkube-base/Dockerfile:30]: not sure whether hyperbube is able to start arktos-network-controller.

File: cluster/gce/config-default.sh [hunk 2]
```diff
@@ -349,6 +350,27 @@ if [[ ! -z "${NODE_ACCELERATORS}" ]]; then
...
+ # By default, this feature is enabled in the dev cluster started by this script.
+DISABLE_NETWORK_SERVICE_SUPPORT="${DISABLE_NETWORK_SERVICE_SUPPORT:-}"
+
+DISABLE_ADMISSION_PLUGINS=${DISABLE_ADMISSION_PLUGINS:-""}
+# check for network service support flags
+if [ -z ${DISABLE_NETWORK_SERVICE_SUPPORT} ]; then # when enabled
+  # kubelet enforces per-network DNS ip in pod
+  FEATURE_GATES="${FEATURE_GATES},MandatoryArktosNetwork=true"
+  # tenant controller automatically creates a default network resource for new tenant
+  if [[ "${NETWORK_PROVIDER:-}" == "mizar" ]]; then
```
[the remark this answers is not in the document]
Comment (sonyafenge) [reply cluster/gce/config-default.sh:364]: yes, this should be part of https://github.com/CentaurusInfra/arktos/issues/1279 fix, for now, I suggest to leave here. because this PR need merge with issue 1279 fix together. let's wait issue 1279 fix and then update if pessary.

[the remark this answers is not in the document]
Comment (q131172019) [reply cluster/gce/config-default.sh:364]: I agree with Sonya.

File: cluster/gce/gci/configure-helper-common.sh [hunk 3]
```diff
@@ -2445,6 +2448,67 @@ function start-workload-controller-manager {
...
+  cp "${src_dir}/crd-network.yaml" ${dst_dir}
+
+  # apply network crd before start network-controller
+  kubectl apply -f "${dst_dir}/crd-network.yaml"
+
+  # Calculate variables and assemble the command line.
+  local params="${ARKTOS_NETWORK_CONTROLLER_TEST_LOG_LEVEL:-"--v=4"}"
+  params+=" --master=http://127.0.0.1:8080"
+  params+=" --kube-apiserver-ip ${KUBERNETES_MASTER_INTERNAL_IP}"
+  if [[ "${USE_INSECURE_SCALEOUT_CLUSTER_MODE:-false}" == "true" ]]; then
```
Comment (h-w-chen) [inline cluster/gce/gci/configure-helper-common.sh:2477]: not sure whether we should use this env as controlling condition.

File: cluster/gce/util.sh [hunk 4]
```diff
@@ -2684,15 +2699,6 @@ function kube-up() {
         create-node-port
       done
       restart_tp_scheduler_and_controller
-
-      # start-kubemark.sh sets KUBEMARK_PREFIX default to 'kubemark'
```
Comment (h-w-chen) [inline cluster/gce/util.sh:2688]: is this deletion of block intended?

**Review by h-w-chen — COMMENTED** [review]
this PR seems dependent on another one. will take a look again after the dependent PR is in place.

**Comment by vinaykul** [comment]
I tried this PR with some minor modifications. For the most part, it does what I need. i.e Package and start arktos-network-controller container. There are some things that need to be done in addition for parity with arktos-up. (create system-default-network object and associated VPC/subnets). With that done, using operator running on tp-master I'm able to bring mizar objects to provisioned state and start pods, but pings don't work.  Creating tenant and getting pods running in the tenant is not working. I'm probably missing steps in the workflow.
Pending Arktos reviews, to me this is LGTM as far as the core purpose of PR is concerned.

File: cluster/gce/gci/configure-helper-common.sh [hunk 5]
```diff
@@ -2445,6 +2448,67 @@ function start-workload-controller-manager {
...
+    params+=" --kube-apiserver-port=6443"
+  else
+    params+=" --kube-apiserver-port=443"
```
[the remark this answers is not in the document]
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper-common.sh:2480]: looks like no certs is required for arktos-network-controller

File: cluster/gce/util.sh (hunk 4 above)
Comment (sonyafenge) [reply cluster/gce/util.sh:2688]: This is moved to master server to reduce cluster operation from dev machine

**Comment by sonyafenge** [comment]
Tested on top of PR #1310.
Scale-up:
```
$ kubectl  get network
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.18.134

$ kubectl get crds
NAME                                    AGE
networks.arktos.futurewei.com           71s
scalingpolicies.scalingpolicy.kope.io   48s

$ kubectl get pods -A | grep arktos
kube-system   arktos-network-controller-sonyaperf1-012722-master   3814323996954979909   1/1     Running             0          6s
```

Scale-out:
```
$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/cluster/kubeconfig-proxy get network
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.200.220

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/cluster/kubeconfig-proxy get crds
NAME                                    AGE
networks.arktos.futurewei.com           10m
scalingpolicies.scalingpolicy.kope.io   10m

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/cluster/kubeconfig-proxy get pods -A | grep network
kube-system   arktos-network-controller-sonyaperf1-012722-tp-1-master   4797376341620962786   1/1     Running             0          10m
```

File: cluster/gce/gci/configure-helper-common.sh (hunk 3 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper-common.sh:2485]: for now, arktos is using USE_INSECURE_SCALEOUT_CLUSTER_MODE for insecure mode. but default, we are using  secure port: 443 to access

**Review by q131172019 — APPROVED** [review]
/LGTM

**Comment by sonyafenge** [comment]
Tested kubemark with below config
1. Admin (scale-up) + kubemark (scale-up) 100 hollow-nodes can be started successfully
```
$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark get network
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.135.251

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark get crds
NAME                            AGE
networks.arktos.futurewei.com   8m9s

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark get pods -A | grep arktos
kube-system   arktos-network-controller-sonyaperf1-012722-kubemark-master   6548999301784634424   1/1     Running             0          6m28s

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark get nodes | wc -l
102
```
2. Admin (scale-up) + kubemark (scale-out: 1tp*1rp) 100 hollow-nodes can be started successfully
```
$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark-proxy get crds
NAME                            AGE
networks.arktos.futurewei.com   11m

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark-proxy get network
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.54.165

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark-proxy get pods -A | grep arktos
kube-system   arktos-network-controller-sonyaperf2-012722-kubemark-tp-1-master   607665849631186957    1/1     Running   0          10m

$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark-proxy get nodes | wc -l
102
```

**Comment by sonyafenge** [comment]
Run perf-tests with below config

1. Admin (scale-up) + kubemark (scale-up) 100 hollow-nodes
```
I0128 01:11:27.970343   20238 clusterloader.go:218] --------------------------------------------------------------------------------
I0128 01:11:27.970349   20238 clusterloader.go:219] Test Finished
I0128 01:11:27.970354   20238 clusterloader.go:220]   Test: testing/density/config.yaml
I0128 01:11:27.970359   20238 clusterloader.go:221]   Status: Success
I0128 01:11:27.970364   20238 clusterloader.go:225] --------------------------------------------------------------------------------

JUnit report was created: /home/sonyali/logs/perf-test/gce-100/arktos/sonyaperf1-012722/junit.xml
```
2. Admin (scale-up) + kubemark (scale-out) 100 hollow-nodes
```
I0128 01:05:39.316806   24609 clusterloader.go:218] --------------------------------------------------------------------------------
I0128 01:05:39.316814   24609 clusterloader.go:219] Test Finished
I0128 01:05:39.316819   24609 clusterloader.go:220]   Test: testing/density/config.yaml
I0128 01:05:39.316824   24609 clusterloader.go:221]   Status: Success
I0128 01:05:39.316829   24609 clusterloader.go:225] --------------------------------------------------------------------I0128 01:05:39.316829   24609 clusterloader.go:225] --------------------------------------------------------------------------------

JUnit report was created: /home/sonyali/logs/perf-test/gce-100/arktos/sonyaperf2-012722/arktos/junit.xml
```
