### PR TITLE
fix issue 1038. kubeconfig for kcm on TP to use the proxy till the KCM supports direct talk to RPs

### LINKED ISSUE #1038: KCM on TP cluster didn't get nodes in RP cluster(s)
**What happened**:
KCM on TP cluster didn't get the nodes and in turn, the gc-controller kicks in treating pods on hollow nodes as Orphaned.

the cause of this issue is the KCM use a kubeconfig that directly talks to its own cluster api servers, while the --resource-provider support is NOT checked in yet.

```
I0319 20:43:08.030928       1 gc_controller.go:162] Found orphaned Pod 43oa7b-testns/saturation-deployment-0-c47675f5-cs2l5 assigned to the Node hollow-node-8zcvp. Deleting.
I0319 20:43:08.032674       1 gc_controller.go:162] Found orphaned Pod 43oa7b-testns/saturation-deployment-0-c47675f5-ht9x4 assigned to the Node hollow-node-7rhx2. Deleting.
I0319 20:43:08.034746       1 gc_controller.go:162] Found orphaned Pod 43oa7b-testns/saturation-deployment-0-c47675f5-n5v5b assigned to the Node hollow-node-bm5xs. Deleting.
I0319 20:43:08.036744       1 gc_controller.go:162] Found orphaned Pod 43oa7b-testns/saturation-deployment-0-c47675f5-7ggdx assigned to the Node hollow-node-s5fd6. Deleting.
```
**What you expected to happen**:
the KCM on TP should get all the nodes from RP cluster(s). with either one of below:
1. KCM connect to the proxy.  --- previous Arktos behavior
2. KCM to support direct talk to RP cluster(s).  --- this is what is under testing in 430 POC branch
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by yb01**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
fix bug in KCM on TP cluster to talk to the proxy instead of pointing to the local cluster --- the RP directly connect from KCM on TP is not yet supported in main -- it is currently tested in 430 branch

**Which issue(s) this PR fixes**:

Fixes #1038 

**Special notes for your reviewer**:
unblock perf testing in master branch. essential changes is 
```
if [[ "${KUBERNETES_TENANT_PARTITION:-false}" == "true" ]]; then
    create-kubeconfig "kube-controller-manager" ${KUBE_CONTROLLER_MANAGER_TOKEN} "${PROXY_RESERVED_IP}" "443" "https"
```

**Does this PR introduce a user-facing change?**:
none 

**Testing:
1. 1 TP, 1 RP scaleout
2. scaleup test

verified bug fix:
```
ybai2016@yb01-multiple-rp-kubemark-tp-1-master /var/log $ grep -i "Found orphaned Pod" kube-controller-manager.log
ybai2016@yb01-multiple-rp-kubemark-tp-1-master /var/log $
```

### CODE REVIEW

File: cluster/gce/gci/configure-helper-common.sh [hunk 1]
```diff
@@ -597,7 +597,8 @@ function create-master-auth {
     append_or_replace_prefixed_line "${known_tokens_csv}" "${KUBE_BOOTSTRAP_TOKEN},"          "gcp:kube-bootstrap,uid:gcp:kube-bootstrap,system:masters"
   fi
   if [[ -n "${KUBE_CONTROLLER_MANAGER_TOKEN:-}" ]]; then
-    append_or_replace_prefixed_line "${known_tokens_csv}" "${KUBE_CONTROLLER_MANAGER_TOKEN}," "system:kube-controller-manager,uid:system:kube-controller-manager"
+    ## workaround for Arktos issue 1039, to treat the KCM token as admin
+    append_or_replace_prefixed_line "${known_tokens_csv}" "${KUBE_CONTROLLER_MANAGER_TOKEN}," "admin,admin,system:masters"
```
Comment (Sindica) [inline cluster/gce/gci/configure-helper-common.sh:601]: Not sure how this would work. Also it does not look good for master

Comment (yb01) [reply cluster/gce/gci/configure-helper-common.sh:601]: this is not new in this PR. it is just a different way to workaround bug 1039 as it commented out. previously the workaround is to use the bootstrap kubeconfig.

**Comment by yb01** [comment]
we are verifying to integrate with bug fix 1039. so for now, please do not merge this PR.

**Review by sonyafenge — APPROVED** [review]
/LGTM

File: cluster/gce/gci/configure-helper-common.sh (hunk 1 above)
Comment (yb01) [reply cluster/gce/gci/configure-helper-common.sh]: fixed

**Review by XiaoningDing — APPROVED** [review]
