### PR TITLE
[kube-up][scale-out]Automatically create default mizar vpc and subnet for tenants 

### LINKED ISSUE #1322: [kube-up][scale-out] Default VPC object of system tenant is  not created
**What happened**:

Default VPC object of system tenant is  not automatically created.

```
kubectl get vpc
NAME   IP         PREFIX   VNI   DIVIDERS   STATUS        CREATETIME                   PROVISIONDELAY
vpc0   20.0.0.0   8        1     1          Provisioned   2022-01-31T19:21:27.098916   101.317413
```

**What you expected to happen**:
The default vpc object "system-default-network" should be created and seen.

**How to reproduce it (as minimally and precisely as possible)**:
In scale-out 1 x 1 kubeup with mizar PR1320, on tp-1 master, run command "kubectl get vpc".

**Anything else we need to know?**:
Based on poc-2022-01-30 plus mizar PR1320.

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:  scale-out 1 x 1 kubeup
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by q131172019**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind feature

**What this PR does / why we need it**:
The PR is to enable the feature - automatically create the default mizar VPC and Subnets objects for all tenants including system tenant and non-system tenants after scale out 1 x 1 cluster or scale-up cluster of KUBE-UP environment starts.

System tenant: 
``` 
vpc - system-default-network 
subnet - system-default-network-subnet
```

Non-system tenant: 
```
vpc - {{tenant name}}-default-network
subnet - {{tenant name}}-default-network-subnet 
```

If network support is not desired, setting environment variable DISABLE_NETWORK_SERVICE_SUPPORT to true will disable this feature; in the meantime, if NETWORK_PROVIDER is set to 'mizar', the vpc 'vpc0' and subnet 'net0' are still automatically created,

**Which issue(s) this PR fixes**:
Fixes #1322 

To simplify the code review, the issue #1326 will be fixed by another PR 1331.

**Special notes for your reviewer**:
This PR is the follow-up of the PR1310 and PR1298.

The POC test environment also contains mizar PR1320.

**Does this PR introduce a user-facing change?**:

The following 8 cases in kubeup environment are tested without new issues.
1x1 scale-out cluster with mizar and DISABLE_NETWORK_SERVICE_SUPPORT is unset
1x1 scale-out cluster with flat and DISABLE_NETWORK_SERVICE_SUPPORT is unset
scale-up cluster with mizar and DISABLE_NETWORK_SERVICE_SUPPORT is unset
scale-up cluster with flat and DISABLE_NETWORK_SERVICE_SUPPORT is unset

1x1 scale-out cluster with mizar and DISABLE_NETWORK_SERVICE_SUPPORT=true
1x1 scale-out cluster with flat and DISABLE_NETWORK_SERVICE_SUPPORT=true
scale-up cluster with mizar and DISABLE_NETWORK_SERVICE_SUPPORT=true
scale-up cluster with flat and DISABLE_NETWORK_SERVICE_SUPPORT=true

Additional case in local dev environment is tested without new issue because there are minor code changes in cmd/kube-controller-manager/app/mizarcontrollers.go. 

make clean; CNIPLUGIN=mizar ./hack/arktos-up.sh

### CODE REVIEW

File: cluster/common.sh [hunk 1]
```diff
@@ -942,9 +942,9 @@ EOF
 DISABLE_NETWORK_SERVICE_SUPPORT: $(yaml-quote ${DISABLE_NETWORK_SERVICE_SUPPORT})
 EOF
     fi
-    if [ -n "${DISABLE_ADMISSION_PLUGINS:-}" ]; then
```
Comment (h-w-chen) [inline cluster/common.sh:945]: do you really want to get rid of DISABLE_ADMISSION_PLUGINS env var?

File: cluster/gce/gci/configure-helper-common.sh [hunk 2]
```diff
@@ -2358,7 +2355,7 @@ function start-kube-controller-manager {
   if [[ -n "${RUN_CONTROLLERS:-}" ]]; then
     params+=" --controllers=${RUN_CONTROLLERS}"
   fi
-  if [[ -s ${DEFAULT_NETWORK_TEMPLATE} && -z "${DISABLE_NETWORK_SERVICE_SUPPORT:-}" ]]; then
+  if [[ -z "${DISABLE_NETWORK_SERVICE_SUPPORT:-}" && -s ${DEFAULT_NETWORK_TEMPLATE} ]]; then
```
Comment (h-w-chen) [inline cluster/gce/gci/configure-helper-common.sh:2358]: the changed line is identical to the original, isn't it?

File: cluster/gce/gci/configure-helper.sh [hunk 3]
```diff
@@ -53,6 +53,9 @@ function main() {
   CONTAINERIZED_MOUNTER_HOME="${KUBE_HOME}/containerized_mounter"
   PV_RECYCLER_OVERRIDE_TEMPLATE="${KUBE_HOME}/kube-manifests/kubernetes/pv-recycler-template.yaml"
   DEFAULT_NETWORK_TEMPLATE="${KUBE_HOME}/kube-manifests/kubernetes/default-network.tmpl"
+  DEFAULT_PATH="/hack/runtime"
+  DEFAULT_VPC_TEMPLATE_PATH="${DEFAULT_PATH}/default_mizar_network_vpc_template.json"
```
Comment (h-w-chen) [inline cluster/gce/gci/configure-helper.sh:57]: is DEFAULT_PATH a new env var introduced here?

File: cluster/gce/gci/configure-helper-common.sh [hunk 4]
```diff
@@ -3461,6 +3484,23 @@ function create-default-network-template-volume-mount {
   DEFAULT_NETWORK_TEMPLATE_PATH_MOUNT="{\"name\": \"defaulttemplate\",\"mountPath\": \"${DEFAULT_NETWORK_TEMPLATE}\", \"readOnly\": false},"
 
   cat > ${DEFAULT_NETWORK_TEMPLATE} < ${KUBE_HOME}/network.tmpl
+
+  if [[ "${NETWORK_PROVIDER:-}" == "mizar" ]]; then
+    if [[ -z "${DEFAULT_VPC_TEMPLATE_PATH:-}" || -z "${DEFAULT_SUBNET_TEMPLATE_PATH:-}" ]]; then
```
Comment (h-w-chen) [inline cluster/gce/gci/configure-helper-common.sh:3489]: mot

**Comment by Sindica** [comment]
So much changes are needed in order to upload a template file. It is better using json type struct instead of template file.

File: cluster/common.sh [hunk 5]
```diff
@@ -942,9 +942,9 @@ EOF
...
+    if [ -n "${NETWORK_PROVIDER:-}" ]; then
       cat >>$file <<EOF
-DISABLE_ADMISSION_PLUGINS: $(yaml-quote ${DISABLE_ADMISSION_PLUGINS})
+NETWORK_PROVIDER: $(yaml-quote ${NETWORK_PROVIDER})
```
Comment (sonyafenge) [inline cluster/common.sh:947]: This already included in the same function:  line#792
```
NETWORK_PROVIDER: $(yaml-quote ${NETWORK_PROVIDER:-})
```

Comment (h-w-chen) [inline cluster/common.sh:947]: NETWORK_PROVIDER seems already have been processed that way.

File: cluster/gce/gci/configure.sh [hunk 6]
```diff
@@ -255,6 +255,40 @@ function download-network-template {
   )
 }
 
+function download-vpc-template {
```
Comment (h-w-chen) [inline cluster/gce/gci/configure.sh:258]: download file seems a very common op; suggest to refactor and reuse.

File: cluster/gce/gci/configure-helper.sh [hunk 7]
```diff
@@ -53,6 +53,9 @@ function main() {
   CONTAINERIZED_MOUNTER_HOME="${KUBE_HOME}/containerized_mounter"
   PV_RECYCLER_OVERRIDE_TEMPLATE="${KUBE_HOME}/kube-manifests/kubernetes/pv-recycler-template.yaml"
   DEFAULT_NETWORK_TEMPLATE="${KUBE_HOME}/kube-manifests/kubernetes/default-network.tmpl"
+  DEFAULT_PATH="/hack/runtime"
```
Comment (sonyafenge) [inline cluster/gce/gci/configure-helper.sh:56]: "/hack/runtime" looks like a Dev machine folder, should we change this to match with other file folder?

File: cluster/gce/gci/scaleoutserver-helper.sh [hunk 8]
```diff
@@ -160,9 +160,17 @@ function create-scaleoutserver-instance-internal() {
   metadata="${metadata},kube-master-certs=${KUBE_TEMP}/kube-master-certs.yaml"
   metadata="${metadata},cluster-location=${KUBE_TEMP}/cluster-location.txt"
   metadata="${metadata},controllerconfig=${KUBE_TEMP}/controllerconfig.json"
-  if [[ -s ${KUBE_TEMP}/network.tmpl ]]; then
+  if [[ -z "${DISABLE_NETWORK_SERVICE_SUPPORT}" && -s ${KUBE_TEMP}/network.tmpl ]]; then
     metadata="${metadata},networktemplate=${KUBE_TEMP}/network.tmpl"
   fi
+
+  if [[ -z "${DISABLE_NETWORK_SERVICE_SUPPORT}" && "${NETWORK_PROVIDER:-}" == "mizar" ]]; then
```
Comment (sonyafenge) [inline cluster/gce/gci/scaleoutserver-helper.sh:167]: if DISABLE_NETWORK_SERVICE_SUPPORT=true, can we still use mizar as NETWORK_PROVIDER?

**Review by h-w-chen — APPROVED** [review]
lgtm.
Based on the fact that it has been tested, it meets the bar of POC.

File: cluster/common.sh (hunk 1 above)
Comment (q131172019) [reply cluster/common.sh:945]: Kubeup API server uses admission-control whereas local dev environment uses enable-admission-plugins/disable-admission-plugins. So the parameter "DISABLE_ADMISSION_PLUGINS" is removed because of conflicting with admission-control.

File: cluster/gce/gci/configure-helper.sh (hunk 3 above)
Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:57]: This env is to match the path defined in golang code line 45 in cmd/kube-controller-manager/app/mizarcontrollers.go.

homeSubPath        = "/hack/runtime/"

File: cluster/common.sh (hunk 5 above)
Comment (q131172019) [reply cluster/common.sh:947]: Thank you. good to know. will remove this line.

Comment (q131172019) [reply cluster/common.sh:947]: Yes, will remove this duplicate code.

File: cluster/gce/gci/configure.sh (hunk 6 above)
Comment (q131172019) [reply cluster/gce/gci/configure.sh:258]: Consider do this and should be quick fix.

File: cluster/gce/gci/configure-helper.sh (hunk 7 above)
Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:56]: This env is to match the path defined in golang code line 45 in cmd/kube-controller-manager/app/mizarcontrollers.go.

homeSubPath = "/hack/runtime/"

File: cluster/gce/gci/scaleoutserver-helper.sh (hunk 8 above)
Comment (q131172019) [reply cluster/gce/gci/scaleoutserver-helper.sh:167]: if DISABLE_NETWORK_SERVICE_SUPPORT=true,  the boolean value of "-z "${DISABLE_NETWORK_SERVICE_SUPPORT}" is false,  the NETWORK_PROVIDER  is not checked.

If DISABLE_NETWORK_SERVICE_SUPPORT is not set, NETWORK_PROVIDER will be checked.

**Comment by q131172019** [comment]
>>>So much changes are needed in order to upload a template file. It is better using >>>json type struct instead of template file.

This is better way. I support it.

But the PR is a quick fix to two issues and do not want to block mizar team's further tests.

The new code changes using json type struct are related to new golang codes. which need to be tested in both local dev and kubeup environment. Need more time to make this improvement.

File: cluster/gce/gci/configure-helper.sh (hunk 7 above)
Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:56]: Ever think another idea: first download the template file into ${KUBE_HOME}/kube-manifests/kubernetes/<filename>, then create soft link /hack/runtime/<filename> to ${KUBE_HOME}/kube-manifests/kubernetes/<filename>

File: cluster/gce/gci/scaleoutserver-helper.sh (hunk 8 above)
Comment (q131172019) [reply cluster/gce/gci/scaleoutserver-helper.sh:167]: If DISABLE_NETWORK_SERVICE_SUPPORT=true, we confirm to still use mizar as NETWORK_PROVIDER

File: cluster/common.sh (hunk 5 above)
Comment (q131172019) [reply cluster/common.sh]: Removed duplicate codes.

Comment (q131172019) [reply cluster/common.sh]: Done.

File: cluster/gce/gci/configure.sh (hunk 6 above)
Comment (q131172019) [reply cluster/gce/gci/configure.sh]: Use new function 'download-template-file' to replace 3 functions - download-network-template, download-vpc-template, download-subnet-template

File: cluster/gce/gci/scaleoutserver-helper.sh (hunk 8 above)
Comment (q131172019) [reply cluster/gce/gci/scaleoutserver-helper.sh]: The newest commit ensures if DISABLE_NETWORK_SERVICE_SUPPORT=true, NETWORK_PROVIDER=mizar  still works - vpc0 and net0 are still automatically created.

File: cluster/gce/gci/configure-helper.sh (hunk 7 above)
Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:56]: In master branch, will use json struct object to replace json template file and finally fix the above concern.

File: cluster/common.sh (hunk 1 above)
Comment (h-w-chen) [reply cluster/common.sh]: will be handled by separate focused PR

File: cluster/gce/gci/configure-helper.sh (hunk 7 above)
Comment (sonyafenge) [reply cluster/gce/gci/configure-helper.sh:56]: This kind of hard code should be avoided from source code.

Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:56]: The parameter '--default-network-template-path' for kube-controller-manager is provided, so we can set default-network-template-path to any path which we want.

--default-network-template-path=/home/kubernetes/kube-manifests/kubernetes/default-network.tmpl

But no parameters of vpc template and subnet template are provided for mizar-arktos-network-controller transferred by kube-controller-manager, so currently /hack/runtime is temporarily used.

```
ubuntu@ip-172-31-14-204:~/go/src/arktos$ ls -al ./hack/runtime
total 40
drwxrwxr-x  2 ubuntu ubuntu  4096 Jan 27 22:30 .
drwxrwxr-x 14 ubuntu ubuntu 12288 Feb  2 02:05 ..
-rw-rw-r--  1 ubuntu ubuntu   154 Dec  7 19:58 default_flat_network.json
-rw-rw-r--  1 ubuntu ubuntu   197 Dec  7 19:58 default_mizar_network.json
-rw-rw-r--  1 ubuntu ubuntu   285 Jan 27 22:30 default_mizar_network_subnet_template.json
-rw-rw-r--  1 ubuntu ubuntu   230 Jan 27 22:30 default_mizar_network_vpc_template.json
-rw-rw-r--  1 ubuntu ubuntu   333 Dec  7 19:58 workload-controller-manager-clusterrole.yaml
-rw-rw-r--  1 ubuntu ubuntu   321 Dec  7 19:58 workload-controller-manager-clusterrolebinding.yaml
```

Comment (q131172019) [reply cluster/gce/gci/configure-helper.sh:56]: If the following parameters are provided for kube-controller-manager, the situation will be better, but new codes have to be added into tenant-controller.  However, we decide to use json struct object to replace json template file to avoid using hard code "/hack/runtime".

--default-vpc-template-path
--default-template-template-path

**Review by sonyafenge — APPROVED** [review]
/LGTM
Approve per  meet pod bar

File: cluster/gce/gci/configure-helper-common.sh [hunk 9]
```diff
@@ -1805,9 +1805,6 @@ function start-kube-apiserver {
   if [[ -n "${ENABLE_GARBAGE_COLLECTOR:-}" ]]; then
     params+=" --enable-garbage-collector=${ENABLE_GARBAGE_COLLECTOR}"
   fi
```
[the remark this answers is not in the document]
Comment (q131172019) [reply cluster/gce/gci/configure-helper-common.sh:1807]: yes. The reason is  kube-api server is not up and get error:

"admission-control and enable-admission-plugins/disable-admission-plugins flags are mutually exclusive"

[the remark this answers is not in the document]
Comment (Sindica) [reply cluster/gce/gci/configure-helper-common.sh:1807]: This fixed error introduced in PR 1310
