### PR TITLE
bug fix: static pods are constantly recycled

### LINKED ISSUE #1042: [branch 430] controllers on TP should union the nodes from RP cluster and local cluster
**What happened**:
currently when the controller get node, it ONLY get from the RP controllers, in turn, the static pods on local cluster were GCed and cycled ( created-GCed-recreated....)

i.e. this function should also include the local cluster's node:

```
func (gcc *PodGCController) gcOrphaned(pods []*v1.Pod) {
	klog.V(4).Infof("GC'ing orphaned")
	// We want to get list of Nodes from the etcd, to make sure that it's as fresh as possible.

	// get nodes from resource provider clients
	allRpNodes := make(map[string]*v1.NodeList, len(gcc.resourceProviderClients))
	errs := make(map[string]error, len(gcc.resourceProviderClients))
	var wg sync.WaitGroup
	wg.Add(len(gcc.resourceProviderClients))
	var lock sync.Mutex
	for rpId, client := range gcc.resourceProviderClients {
		go func(resourceProviderId string, rpClient clientset.Interface, nodeLists map[string]*v1.NodeList, errs map[string]error, writeLock *sync.Mutex) {
			defer wg.Done()
			nodes, err := rpClient.CoreV1().Nodes().List(metav1.ListOptions{})
			if err != nil {
				writeLock.Lock()
				errs[resourceProviderId] = err
				klog.Errorf("Error listing nodes. err: %v", errs)
				writeLock.Unlock()
				return
			}
			writeLock.Lock()
			nodeLists[resourceProviderId] = nodes
			writeLock.Unlock()
		}(rpId, client, allRpNodes, errs, &lock)
	}
	wg.Wait()

	// check errors and aggregate nodes
	if len(errs) == len(gcc.resourceProviderClients) {
		// avoid garbage collection when
		klog.Errorf("Error listing nodes from all resource partition. err: %v", errs)
		return
	}

	nodeNames := sets.NewString()
	for _, nodes := range allRpNodes {
		for _, node := range nodes.Items {
			nodeNames.Insert(node.Name)
		}
	}

............ 
```
```
I0322 17:04:15.176130       1 gc_controller.go:195] Found orphaned Pod system/kube-system/etcd-server-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.209448       1 gc_controller.go:195] Found orphaned Pod system/kube-system/kube-scheduler-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.218002       1 gc_controller.go:195] Found orphaned Pod system/kube-system/etcd-empty-dir-cleanup-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.224984       1 gc_controller.go:195] Found orphaned Pod system/kube-system/etcd-server-events-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.237561       1 gc_controller.go:195] Found orphaned Pod system/kube-system/etcd-server-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.246049       1 gc_controller.go:195] Found orphaned Pod system/kube-system/kube-controller-manager-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.254343       1 gc_controller.go:195] Found orphaned Pod system/kube-system/kube-addon-manager-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
I0322 17:04:35.263104       1 gc_controller.go:195] Found orphaned Pod system/kube-system/kube-apiserver-yb01-multiple-rp-kubemark-tp-1-master assigned to the Node yb01-multiple-rp-kubemark-tp-1-master. Deleting.
```

### PR DESCRIPTION
**Pull request by h-w-chen**
__This PR goes to POC 430 branch only.__

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
GC controller, as part of kube-controller-manager, list nodes, and delete pods if their nodes are gone. In scale-out env, GCC currently list nodes from RPs only; for static pods run from TP itself, it considers them as garbage and recycles them.

This PR changes GCC to include its own TP as one of the node sources.

**Which issue(s) this PR fixes**:
Fixes #1042

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

File: pkg/controller/podgc/gc_controller.go [hunk 1]
```diff
@@ -201,6 +186,32 @@ func (gcc *PodGCController) gcOrphaned(pods []*v1.Pod) {
 	}
 }
 
+func getFreshNodes(nodeListers map[string]clientset.Interface) (map[string]*v1.NodeList, map[string]error) {
```
Comment (yb01) [inline pkg/controller/podgc/gc_controller.go:189]: maybe getLatestNodes() a better name than getFreshNodes()?

**Review by yb01 — APPROVED** [review]
/lgtm

File: pkg/controller/podgc/gc_controller.go [hunk 2]
```diff
@@ -44,7 +44,9 @@ const (
 
 type PodGCController struct {
 	kubeClient              clientset.Interface
-	resourceProviderClients map[string]clientset.Interface
+
+	// all clients to list nodes it cares about, particularly including the current TP client
+	nodeListers map[string]clientset.Interface
```
Comment (Sindica) [inline pkg/controller/podgc/gc_controller.go:49]: We typically use resourceListers for special purpose. Such as podLister in lin 51. Based on kubeClient, perhaps this one can be renamed as kubeClientForNodes or resourceClients, etc.

File: pkg/controller/podgc/gc_controller.go (hunk 1 above)
Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go]: renamed as suggested.

File: pkg/controller/podgc/gc_controller.go (hunk 2 above)
Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go]: renamed as suggested.

File: pkg/controller/podgc/gc_controller.go [hunk 3]
```diff
@@ -59,14 +61,18 @@ func NewPodGC(kubeClient clientset.Interface, rpClients map[string]clientset.Int
...
 		kubeClient:              kubeClient,
-		resourceProviderClients: rpClients,
 		terminatedPodThreshold:  terminatedPodThreshold,
 		deletePod: func(tenant, namespace, name string) error {
 			klog.Infof("PodGC is force deleting Pod: %v/%v/%v", tenant, namespace, name)
 			return kubeClient.CoreV1().PodsWithMultiTenancy(namespace, tenant).Delete(name, metav1.NewDeleteOptions(0))
 		},
 	}
 
+	gcc.kubeClientForNodes = map[string]clientset.Interface{"tpself": kubeClient}
```
Comment (Sindica) [inline pkg/controller/podgc/gc_controller.go:71]: For scale up case, there will be duplicated kubeclients

Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go:71]: good point; looked at code, it seems "0" key is the special case for TP client, which could help to avoid double tp clients.

File: pkg/controller/podgc/gc_controller.go [hunk 4]
```diff
@@ -59,14 +61,20 @@ func NewPodGC(kubeClient clientset.Interface, rpClients map[string]clientset.Int
...
 			klog.Infof("PodGC is force deleting Pod: %v/%v/%v", tenant, namespace, name)
 			return kubeClient.CoreV1().PodsWithMultiTenancy(namespace, tenant).Delete(name, metav1.NewDeleteOptions(0))
 		},
 	}
 
+	// key "0" is special case for TP client itself
+	// todo: avoid using magic literal "0"
+	gcc.kubeClientForNodes = map[string]clientset.Interface{"0": kubeClient}
+	for key, value := range rpClients {
+		gcc.kubeClientForNodes[key] = value
```
Comment (Sindica) [inline pkg/controller/podgc/gc_controller.go:75]: The key for rpClients is rp0, rp1, etc.

**Review by Sindica — APPROVED** [review]
/lgtm

File: pkg/controller/podgc/gc_controller.go [hunk 5]
```diff
@@ -201,6 +188,32 @@ func (gcc *PodGCController) gcOrphaned(pods []*v1.Pod) {
 	}
 }
 
+func getLatestNodes(nodeListers map[string]clientset.Interface) (map[string]*v1.NodeList, map[string]error) {
```
Comment (Sindica) [inline pkg/controller/podgc/gc_controller.go:191]: Can we rename nodeListers as kubeClientForNodes as well?

Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go]: renamed to kubeClients

File: pkg/controller/podgc/gc_controller.go [hunk 6]
```diff
@@ -59,14 +61,20 @@ func NewPodGC(kubeClient clientset.Interface, rpClients map[string]clientset.Int
...
 		terminatedPodThreshold:  terminatedPodThreshold,
 		deletePod: func(tenant, namespace, name string) error {
 			klog.Infof("PodGC is force deleting Pod: %v/%v/%v", tenant, namespace, name)
 			return kubeClient.CoreV1().PodsWithMultiTenancy(namespace, tenant).Delete(name, metav1.NewDeleteOptions(0))
 		},
 	}
 
+	// key "0" is special case for TP client itself
+	// todo: avoid using magic literal "0"
+	gcc.kubeClientForNodes = map[string]clientset.Interface{"0": kubeClient}
```
Comment (Sindica) [inline pkg/controller/podgc/gc_controller.go:73]: Checked scale up and scale out log again. Scale out has following log:
I0324 02:06:19.186483       1 gc_controller.go:195] Found orphaned Pod system/kube-system/etcd-server-events-poc430-032321-2tp2rpx500-kubemark-tp-1-master assigned to the Node poc430-032321-2tp2rpx500-kubemark-tp-1-master. Deleting.

But scale up does not have any.
sonya-uswest2:/home/sonyali/logs/perf-test/gce-500/arktos/up-poc430-032321-500/logs/kubemark_master/log

I suspect that in case of scale up, resourceProviderClients will take kubeClient as its value. That's why I this log could cause double kubeclients to node query.

**Review by Sindica — CHANGES_REQUESTED** [review]
Please check in scale up case to make sure there will be single client to list nodes

File: pkg/controller/podgc/gc_controller.go (hunk 6 above)
Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go:73]: looked at the relevant code, for scale up (not scale out), gcc is created w/ this param as nil map - which implies double putting is not an issue; for scale out, this param passed in as map of RP clients, which disregards double putting too.

Comment (h-w-chen) [reply pkg/controller/podgc/gc_controller.go:73]: Turns out there seems an existing defect in the current code which cannot list nodes for scale-up case.
 
Looked at sonya-uswest2:/home/sonyali/logs/perf-test/gce-500/arktos/up-poc430-032321-500/logs/kubemark_master/log/kube-controller-manager.log, there were a lot of error message
```
E0324 02:25:09.522145       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:25:29.522666       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:25:49.523044       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:26:09.523463       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:26:29.523887       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:26:49.524245       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:27:09.524656       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:27:29.525092       1 gc_controller.go:177] Error listing nodes from all resource partition. err: map[]
E0324 02:27:49.525469     ...
```

WRT this PR, it seems double-dipping out of question. Actually, it seems able to fix the aforementioned defect.

Comment (Sindica) [reply pkg/controller/podgc/gc_controller.go:73]: Thanks for checking this out

**Review by Sindica — APPROVED** [review]
